version: '3.8'

services:
  app:
    image: ghcr.io/danielhep/go-elections
    entrypoint: election-scraper
    environment:
      - PG_URL=postgres://postgres:postgres@db:5432/elections?sslmode=disable
      - STATE_DATA=https://results.vote.wa.gov/results/20240806/export/20240806_AllState.csv
      - COUNTY_DATA=https://aqua.kingcounty.gov/elections/2024/aug-primary/webresults.csv
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: elections
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  postgraphile:
    image: graphile/postgraphile
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/elections
      SCHEMA: public
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: ["--watch", "--enhance-graphiql", "--allow-explain"]

volumes:
  postgres-data: